# Generated by Django 5.0.4 on 2024-05-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_biodata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biodata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='last_name',
        ),
    ]
