# Generated by Django 5.0.4 on 2024-05-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_biodata_email_remove_biodata_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
